version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
    links:
      - app
    depends_on:
      - app
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
    environment:
      - MEMCACHED_CACHE_SIZE=128
    container_name: memcached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    links:
      - "database"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: secret

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=mydb
    ports:
        - "33061:3306"
    container_name: db_mysql

volumes:
  dbdata: